<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <title>New Technology</title>

    <!-- Mobile Specific Metas
  ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <!-- CSS
  ================================================== -->
    <!-- Bootstrap -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">
     <!-- Prettyphoto -->
    <!-- FontAwesome -->
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <!--Line icon font -->
    <link rel="stylesheet" href="css/line-icons.min.css">
    <!-- Animation -->
    <link rel="stylesheet" href="css/animate.css">
    <!-- Prettyphoto -->
    <link rel="stylesheet" href="css/prettyPhoto.css">
    <!-- styles-->
    <link rel="stylesheet" href="css/style.css">
    <!-- color style -->
    <link rel="stylesheet" href="css/presets/maincolor.css">
    <!-- Responsive styles-->
    <link rel="stylesheet" href="css/responsive.css">
    <!-- circle counter -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    
    <!-- main coding strat -->
    <header id="header" >
    	<nav class="navbar navbar-default navbar-fixed-top"  id="tf-menu">
    	<div class="container">
    		<div class="row">
    			<div class="navbar-header ">
    				<button class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse">
    					<span class="sr-only"></span>
    					<span class="icon-bar"></span>
    					<span class="icon-bar"></span>
    					<span class="icon-bar"></span>
    				</button>
    				<a href="#" class="navbar-brand page-scroll"><img class="" src="img/logo.png" alt="logo"></a>
    			</div> <!-- navabr-header -->

    			<div class="collapse navbar-collapse clearfix" id="bs-example-navbar-collapse-1" role="navigation">
    				<ul class="nav navbar-nav navbar-right">
    					<li><a class="page-scroll" href="index.php#header"> Home</a></li>
    					<li><a class="page-scroll" href="index.php#about">About Us</a></li>
    					<li><a class="page-scroll" href="index.php#work">Work</a></li>
    					<li><a class="page-scroll" href="index.php#sevices">Services</a></li>
    					<li><a class="page-scroll" href="index.php#contact" >Contact</a></li>
    				</ul>
    			</div>
    		</div> <!-- row end -->
    	</div> <!-- container end -->
    	</nav> <!-- nav end -->
    </header>

	<div class="m40"></div>   <br>
		<section id="pst">
		<div class="container">
		<div class="row">
			<div class="col-md-3">
				<h3 class="green">Passive Seismic Tomography (PST)</h3>
			</div>
			
				<img class="img-responsive wow fadeInLeft animated" data-wow-delay=".2" src="img/h1.jpg" alt="header">
							<div class="m40"></div>
			
			<div class="col-md-12">
				<div class="services-content">
				<p style="text-align:justify;">Passive Seismic Tomography (PST) is a technique to image the subsurface of the earth. PST is similar to a CAT scan of the human body, but instead of using X-rays, we use the elastic waves generated by microearthquakes as our energy source. Microearthquakes occur any where in the earth where the background stress field has been perturbed even to a small degree such that data from a producing zone can be imaged from the surface using a well designed seismic network. Any moderately tectonically active region can be imaged using PST, where as a traditional 3D-seismic reflection survey may be impossible. Data collection happens over the course of a few weeks to months (depending on the level of activity in the area). PST is not a new technique and is well established; but only recently started to be used in the oil, gas, and mining industries to image the subsurface.<br>
					<br>
					<p style="text-align:justify;">With PST, we can produce a complete 3D tomography image of the P and S wave velocity beneath the network once enough data have been collected. In addition, we can compute Vp/Vs ratios and hence Poisson's ratio to establish the presence of fluids or geothermal activity within the zone of interest. We can provide equipment and expertise to you with a complete end-to-end PST solution.<br><br> </p>
					<ul>
					<ol>Energy Source of PST: 
					<li>2D and 3D Reflection and Refraction surveys use blasts or vibraseis as the energy source. </li>
					 <li>For PST, microearthquakes are the energy source. </li>
					 <li>Earthquakes are located by a dense array of seismic stations running continuously over the target area. </li>
					 <li>Earthquakes have broader frequency range than active source, and needs better seismometers. </li>
					 <li>LIMITATION: only active tectonic regions or sites with induced seismicity can be imaged. </li>
					</ol>
					<br>
					<ol>Results : 
					<li>3D P and S wave velocity model beneath the network. </li>
					<li>Vp/Vs - Poisson's ratio to determine geophysical properties of the target area. </li>
					<li>Refined earthquake locations on active faults - using double difference technique.</li>
					</ol>
					</ul>
					
		</div>			
		</div>			
		

	<div class="m40"></div>
			
				<div class="col-md-12">
					<img class="img-responsive col-lg-12 wow fadeInLeft animated" data-wow-delay=".2" src="img/h2.jpg" alt="gambar">
					<br>
					
				</div>
				<div class="col-md-12">
				<p > We collaborate with experience geophysical software development and research company in US, Instrumental Software Technologies, Inc. to help us with the high quality analytical services.</p>
				<p>Our strategic partnership :</P>
				<div class="col-md-12">
					<img class="wow fadeInLeft animated" data-wow-delay=".2" src="img/h3.png" alt="dd">
				</div>
			</div>
		</div>
			<div class="m20"></div>
</section>
	<section id="process2" class="process parallax3">
			<div class="parallax-overlay2"></div>
				<div class="col-md-12"><br>

			</div>
	</section>
	
<section  id="sg">
<div class="container">
		<div class="row">
			<div class="col-md-3">
				<h3 class="green">Surface Geochemical</h3>
			</div>
		</div>
		
		<div class="m20"></div>
		
	<div class="row">
				<div class="col-md-4">
					<img class=" img-responsive col-md-10" src="img/h4.png" alt="gambar">
				</div>
					<div class="col-md-8">
						<p style="text-align:justify;">Surface geochemistry is a low-cost effective method for screening large exploration areas, prospect ranking, and development drilling in order to reduce exploration risk, localize seismic survey area and validate high-grade seismic anomalies, "Do structures contain hydrocarbons or water ?".<br>
	The analytical results combined with other geological and geophysical data can be a guideline to determine potential area in exploration and development of petroleum and mineral resources program.</p>
					<p style="text-align:justify;">Our mission is to provide high quality and reliable data to enhance the confidence in both exploration and development stage of petroleum and mineral resources.</p>
			</div>
		
	</div>	
		<div class="m40"></div>
	<div class="row">	
	<div class="container-fluid">
			<div class="col-md-3">
				<img class="col-md-12 img-responsive" src="img/h5.jpg" alt="gambar">
			</div>
			<div class="col-md-3">
				<img  class="col-md-12 img-responsive" src="img/h6.jpg" alt="gambar">
			</div>
			<div class="col-md-6 ">
				<ul>
					<ol> Services :
						<li>VaporTec Passive Soil Gas</li>
						<li>HTTD Soil Gas Hydrocarbons (C6 - C20) by GC/MS </li>
						<li>Fixed Gas (He, H2, N2, Ar, Ne, O2, CO2, CO, H2S)<br> by GC/MicroTCD</li>
						<li>Synchronous Scan Fluorescence (SSF, C6 - C35 Range)</li>
						<li>Other geochemical analysis related to hydrocarbon sources.</li>
					 </ol>
				</ul>
				</div>
	</div>
	</div>
		<div class="container">
		<div class="col-md-12">
		<p style="text-align:justify;">We collaborate with worldwide experience geochemical survey company in US namely Vista Geoscience to help us with the high quality analytical services. All the sample will be conducted by Noras Nusantara and shipped to Vista Geoscience’s Laboratory for analytical services.</p>
		<p style="text-align:justify;">Our strategic partnership :</P>
		<div class="col-md-7">
		<img class="wow fadeInLeft animated col-md-4 img-responsive" data-wow-delay=".2" src="img/h7.png" alt="dd">
		</div>
		</div>
		</div>
</div>		
</section>
<div class="m40"></div>
	<!-- footer start -->

	<footer id="footer">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="footer-desc text-center">
						<div class="logo wow fadeInDown">Noras Nusantara</div>
						<ul class="socail-list list-inline">
							<li><a href="#"><i class="fa fa-facebook wow fadeInLeft" data-wow-delay=".2s"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter wow fadeInLeft" data-wow-delay=".4s"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus wow fadeInLeft" data-wow-delay=".6s"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin wow fadeInLeft" data-wow-delay=".8s"></i></a></li>
							<li><a href="#"><i class="fa fa-dribbble wow fadeInLeft" data-wow-delay="1s"></i></a></li>
							<li><a href="#"><i class="fa fa-rss wow fadeInLeft" data-wow-delay="1.1s"></i></a></li>
						</ul>
					</div>
				</div>
			</div><!-- row end -->
			<div class="row">
				<div class="col-md-12 text-center">
					<div class="copyright-info m20">
         			 &copy; Copyright 2015 Kenji. <span>Designed &amp; developed by- <a href="https://github.com/gunawan92" target="_blank">Front Gun</a></span>
        			</div>
				</div>
			</div><!--/ Row end -->

			<div id="back-to-top" data-spy="affix" data-offset-top="10" class="back-to-top affix">
			 	<a href="#slider" class="page-scroll">
					<button class="btn btn-primary" title="Back to Top"><i class="fa fa-angle-double-up"></i></button>
				</a>
			</div>
		</div><!-- container end -->
	</footer>
	<!-- footer end -->


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="assets/js/bootstrap.min.js"></script>
    <!-- initialize jQuery Library -->
    <script type="text/javascript" src="js/jquery.js"></script>
    <!-- Wow Animation -->
    <script type="text/javascript" src="js/wow.min.js"></script>
    <!-- SmoothScroll -->
    <script type="text/javascript" src="js/smooth-scroll.js"></script>
    <!-- prettyphoto -->
    <script type="text/javascript" src="js/jquery.prettyPhoto.js"></script>
    <!-- Eeasing -->
    <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
    <!-- Counter -->
    <script type="text/javascript" src="js/jquery.counterup.min.js"></script>
    <!-- Waypoints -->
    <script type="text/javascript" src="js/jquery.waypoints.min.js"></script>
    <!-- Google Map API Key Source -->
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <!-- Google Map  Source -->
    <script type="text/javascript" src="js/gmaps.js"></script>
    <script type="text/javascript" src="js/custom.js"></script>
		
  </body>
</html>